"""empty message

Revision ID: ddc46361c88d
Revises: 2e4d438cf22d
Create Date: 2022-01-26 02:39:01.130123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc46361c88d'
down_revision = '2e4d438cf22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'supplier', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier', type_='unique')
    # ### end Alembic commands ###
